### ISSUE TITLE
Issue about the FLOPs presented in the paper

### ISSUE THREAD

**Issue by melohux** [theFoxofSky/ddfnet#16]
Thank you for your excellent work! But I'm wondering how you obtain the 2.3B FLOPs as claimed in your paper. I've tested the FLOPs of the ResNet50 without your ddf module and it already takes 2.3B. As there are some conv2d with channel interaction in your spatial branch, I think the whole FLOPs of your ddfnet is more than 2.3B, which should be about 2.7B under rough estimation.

**Comment by theFoxofSky** [comment]
I report the flops in the paper using the tool "thop".

After seeing your comment, I check it again by writing my own code as follow:

`def ddf_flops(ch, fs, ks=3, r=0.2):
    ks2 = ks ** 2
    fs2 = fs ** 2
    rch = int(ch*r)
    flops = fs2 * ch + (ch * rch + rch * ch * ks2) + ch * ks2  # global pool + channel filters + filter norm
    flops += (ch * ks2 * fs2) + ks2 * fs2  # spatial filters + filter norm
    flops += (ch * ks2 * fs2) * 2  # combine and apply
    return flops


def block_flops(in_ch, mid_ch, out_chs, fs, downsample=False):
    fs2 = fs ** 2
    flops = in_ch * mid_ch * fs2
    flops += mid_ch * fs2  # BN
    if downsample:
        fs = fs//2
        fs2 = fs ** 2
        flops += in_ch * out_chs * fs2
        flops += out_chs * fs2  # BN
    flops += ddf_flops(mid_ch, fs)
    flops += mid_ch * fs2  # BN
    flops += mid_ch * out_chs * fs2
    flops += out_chs * fs2  # BN
    flops += out_chs * fs2  # x + res(x)
    return flops


total_flops = 0
# stem
total_flops += 3 * 64 * 7 * 7 * 112 * 112
total_flops += 64 * 112 * 112  # BN
# stem pooling
total_flops += 64 * 2 * 2 * 56 * 56
# layer 1 (0)
total_flops += block_flops(64, 64, 256, 56)
# layer 1 (1-2)
total_flops += block_flops(256, 64, 256, 56) * 2
# layer2 (0)
total_flops += block_flops(256, 128, 512, 56, True)
# layer2 (1-2)
total_flops += block_flops(512, 128, 512, 28) * 2
# layer3 (0)
total_flops += block_flops(512, 256, 1024, 28, True)
# layer3 (1-5)
total_flops += block_flops(1024, 256, 1024, 14)*5
# layer5 (0)
total_flops += block_flops(1024, 512, 2048, 14, True)
# layer5 (1-2)
total_flops += block_flops(2048, 512, 2048, 7)*2

total_flops += 7 * 7 * 2048   # pooling
total_flops += 2048 * 1000
`
I got only 2.1B using my own code.
Please double-check my flops code and comment if there is anything wrong. Thanks!

**Comment by melohux** [comment]
Thank you for your reply and I think your calculation is basically correct. You have missed some FLOPs for activation function but yes it should be correct for the 2.3B presented in the paper.

**Comment by melohux** [comment]
Hey, I found a problem that in your code, you are using the bottleneck number [2, 3, 5, 2]. However, this is the architecture for resent38 and for resnet50 it should be [3, 4, 6, 3] and the result would be 2.7B.  Is it right?
