### ISSUE TITLE
question about DDF-Up

### ISSUE THREAD

**Issue by sujyQ** [theFoxofSky/ddfnet#17]
Hi. Thanks for nice paper.

1. In DDF-Up module, does the size of guidance feature have to be same as that of input feature?

2. Can you release the code for "joint depth upsampling with DDF-UP"  experiment in Sec. 6?

thx.

**Comment by theFoxofSky** [comment]
Do you have WeChat? That code is very very messy, I have not cleaned it yet. If you wish, I can send your the junk code with the model.

**Comment by sujyQ** [comment]
Sorry i don't have WeChat. You can email me (tn0502wl@ajou.ac.kr). After receive I'll erase my address.

**Comment by theFoxofSky** [comment]
I erase your email address. Please email me for the code and model, in case I forget it.
My email is fs.jingkaizhou@gmail.com

**Comment by rightchose** [comment]
I think there are some errors in ddf.py. And I made some [modify.](https://github.com/rightchose/ddfnet/blob/main/ddf/ddf.py) The code followed can works. But I'm not sure it is right.
```
from ddf import DDFUpPack
model = DDFUpPack(64).cuda()
input = torch.randn((4, 64, 32, 32)).cuda()
output = model(input)
```

**Comment by jannehlamin** [comment]
Thanks for the code sir, well appreciated! Hmmm, In DDF-Up module, does the size of guidance feature have to Bi linearly up sampled. The code doesn't handle the guidance spatial re-size as the DDF-up layers increases
