### ISSUE TITLE
Excuse me, is there a python version of this one? My setup.py prompt CUDA can't compile

### ISSUE THREAD

**Issue by Fateeeeee** [theFoxofSky/ddfnet#5]

**Comment by theFoxofSky** [comment]
What is the ERROR info？

**Comment by theFoxofSky** [comment]
The python implementation will be very slow and memory-consuming. So, I have not implemented the ddf in python

**Comment by Fateeeeee** [comment]
> What is the ERROR info？
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
My system is Arch Linux. I'm not very good at it

**Comment by theFoxofSky** [comment]
Sorry, I am also not familiar with Arch Linux.
